Repository WildCodeSchool/orleans-js-0920-p2-hero-game, pull requests merged in 2020-11, with the labels that each got.

#7 S02_US09_warrior-and-battle
  src/components/cards/Carte_CaptainMarvel-min.png
  src/components/cards/Carte_Flash-min.png
  src/components/cards/Carte_Gamora-min.png
  src/components/cards/Carte_Greenlantern-min.png
  src/components/cards/Carte_Groot-min.png
  src/components/cards/Carte_Harleyquinn-min.png
  src/components/cards/Carte_Hulk-min.png
  src/components/cards/Carte_Invisiblewoman-min.png
  src/components/cards/Carte_Ironman-min.png
  src/components/cards/Carte_Joker-min.png
  src/components/cards/Carte_Medusa-min.png
  src/components/cards/Carte_Mera-min.png
  src/components/cards/Carte_Poisonivy-min.png
  src/components/cards/Carte_QuickSilver-min.png
  src/components/cards/Carte_Spiderman-min.png
  src/components/cards/Carte_Supergirl-min.png
  src/components/cards/Carte_Superman-min.png
  src/components/cards/Carte_Thanos-min.png
  src/components/cards/Carte_Wolwerine-min.png
  src/components/cards/Carte_Wonderwoman-min.png
  src/components/centralCards/AnimAttack.jsx
  src/components/centralCards/CardChoice.jsx
  src/components/centralCards/CardLeave.jsx
  src/components/centralCards/CentralCards.jsx
  src/components/centralCards/centralCard.css
  src/components/pages/Accueil.jsx
  src/components/pages/Jeux.jsx
Labels: corrections done

#8 S03_bug fix
  package-lock.json
  src/App.jsx
  src/components/centralCards/CentralCards.jsx
  src/components/centralCards/centralCard.css
  src/components/footer/Footer.css
  src/components/navbar/Navbar.css
  src/components/navbar/Navbar.jsx
  src/components/pages/Accueil.jsx
  src/components/player/Player.css
  src/components/player/Player.jsx
Labels: reviewed

#10 some last minor fix
  src/App.css
  src/components/Quizz/Quizz.css
  src/components/assets/Carte_Hulk-min.png
  src/components/assets/Carte_Mera-min.png
  src/components/cards/Carte_Hulk-min.png
  src/components/cards/Carte_Mera-min.png
Labels: reviewed

#12 responsive video and button animation
  src/components/player/Player.css
Labels: reviewed

#13 S03_Character-list-Responsive
  src/components/CharacterList/CharacterList.css
Labels: reviewed

#14 S02 style and bug fix
  src/components/player/Player.css
Labels: reviewed

#15 S02 healthbar
  src/components/ElementsReminder/ElementsReminder.css
  src/components/assets/Logo_Big.png
  src/components/assets/VS.png
  src/components/centralCards/CentralCards.jsx
  src/components/centralCards/centralCard.css
  src/components/footer/Footer.jsx
  src/components/footer/Logo_Big.png
Labels: reviewed

#17 S03_US14_dammage
  src/components/centralCards/CentralCards.jsx
Labels: reviewed

#18 Quizz CSS Adjustment
  src/components/Quizz/Quizz.css
  src/components/assets/quizz-bg.jpg
  src/components/centralCards/CentralCards.jsx
Labels: reviewed

#25 S04 us17 opponent
  src/components/CharacterList/CharacterList.css
  src/components/centralCards/AnimAttack.jsx
  src/components/centralCards/AnimAttack1.jsx
  src/components/centralCards/AnimAttack2.jsx
  src/components/centralCards/AnimAttack3.jsx
  src/components/centralCards/AnimAttack4.jsx
  src/components/centralCards/CardChoice.jsx
  src/components/centralCards/CentralCards.jsx
  src/components/centralCards/centralCard.css
  src/components/footer/Footer.css
Labels: reviewed

#22 game rules
  src/components/Rules/Rules.css
  src/components/Rules/Rules.jsx
  src/components/centralCards/CentralCards.jsx
  src/components/footer/Footer.css
  src/components/pages/Accueil.jsx
  src/components/pages/Jeux.jsx
Labels: reviewed

#26 Add your hero
  src/components/centralCards/CentralCards.jsx
  src/components/heroselect/HeroSelect.jsx
  src/components/navbar/Navbar.jsx
Labels: conflicts

#28 Can be add to master
  src/components/centralCards/CentralCards.jsx
Labels: corrections done, reviewed

#29 Merging dev to master
  src/components/CharacterList/CharacterList.css
  src/components/CharacterList/CharacterList.jsx
  src/components/Rules/Rules.css
  src/components/Rules/Rules.jsx
  src/components/centralCards/AnimAttack.jsx
  src/components/centralCards/AnimAttack1.jsx
  src/components/centralCards/AnimAttack2.jsx
  src/components/centralCards/AnimAttack3.jsx
  src/components/centralCards/AnimAttack4.jsx
  src/components/centralCards/CardChoice.jsx
  src/components/centralCards/CentralCards.jsx
  src/components/centralCards/centralCard.css
  src/components/footer/Footer.css
  src/components/heroselect/HeroSelect.jsx
  src/components/navbar/Navbar.jsx
  src/components/pages/Accueil.jsx
  src/components/pages/Jeux.jsx
Labels: reviewed

#30 Update README.md
  README.md
Labels: reviewed

#31 some fix
  src/components/Rules/Rules.css
  src/components/centralCards/AnimAttack1.jsx
  src/components/centralCards/AnimAttack2.jsx
  src/components/centralCards/AnimAttack3.jsx
  src/components/centralCards/AnimAttack4.jsx
  src/components/centralCards/centralCard.css
  src/components/footer/Footer.css
  src/components/navbar/Navbar.css
  src/components/pages/Accueil.jsx
  src/components/pages/ChooseYourHero.jsx
  src/components/pages/Jeux.jsx
Labels: reviewed

#32 25/11 MAJ anim text combat
  src/components/centralCards/AnimAttack1.jsx
  src/components/centralCards/AnimAttack2.jsx
  src/components/centralCards/AnimAttack3.jsx
  src/components/centralCards/AnimAttack4.jsx
  src/components/centralCards/CentralCards.jsx
  src/components/centralCards/centralCard.css
Labels: reviewed

#33 refont btn replay
  public/index.html
  src/components/centralCards/centralCard.css
Labels: reviewed

#34 Fix button play
  public/index.html
  src/components/Rules/Rules.css
  src/components/assets/down-arrow.png
  src/components/assets/facebook(2).png
  src/components/assets/instagram.png
  src/components/centralCards/CentralCards.jsx
  src/components/centralCards/centralCard.css
  src/components/heroselect/HeroSelect.css
  src/components/pages/Jeux.jsx
  src/components/player/Player.css
  src/components/player/Player.jsx
Labels: reviewed

#36 Responsive game
  README.md
  public/index.html
  src/components/Rules/Rules.css
  src/components/assets/down-arrow.png
  src/components/assets/down.png
  src/components/assets/facebook(2).png
  src/components/assets/instagram.png
  src/components/centralCards/AnimAttack1.jsx
  src/components/centralCards/AnimAttack2.jsx
  src/components/centralCards/AnimAttack3.jsx
  src/components/centralCards/AnimAttack4.jsx
  src/components/centralCards/CentralCards.jsx
  src/components/centralCards/centralCard.css
  src/components/footer/Footer.css
  src/components/heroselect/HeroSelect.css
  src/components/pages/Accueil.jsx
  src/components/pages/ChooseYourHero.jsx
  src/components/pages/Jeux.jsx
  src/components/player/Player.css
  src/components/player/Player.jsx
Labels: reviewed

#37 Fix router
  src/components/navbar/Navbar.css
  src/components/navbar/Navbar.jsx
  src/components/player/Player.css
  src/components/player/Player.jsx
Labels: conflicts

#39 Responsive game
  src/components/player/Player.jsx
Labels: reviewed

#40 Fix link
  src/App.jsx
  src/components/CharacterList/CharacterList.jsx
  src/components/Quizz/Quizz.jsx
  src/components/footer/Footer.jsx
  src/components/navbar/Navbar.css
  src/components/navbar/Navbar.jsx
  src/components/player/Player.jsx
Labels: reviewed

#41 Dev to master
  public/index.html
  src/App.jsx
  src/components/CharacterList/CharacterList.jsx
  src/components/Quizz/Quizz.jsx
  src/components/centralCards/centralCard.css
  src/components/footer/Footer.jsx
  src/components/navbar/Navbar.css
  src/components/navbar/Navbar.jsx
  src/components/player/Player.css
  src/components/player/Player.jsx
Labels: reviewed

#42 Fix effect
  src/components/CharacterList/CharacterList.jsx
  src/components/Quizz/Quizz.jsx
Labels: reviewed
